### ISSUE TITLE
Infinite Loop in sum_even_fibonacci.py

### ISSUE THREAD

**Issue by DocDomergue** [DocDomergue/Open-Source-Project#5]
**Description**

The program never ends and produces no output

**Steps to Reproduce**

Run the program and it will always get caught in a loop

**Expected Behavior**

The program should output 4613732

**Actual Behavior**

The program starts but loops forever

**Additional Information**

Operating System: MacOS Ventura 13.2.1
Browser: Opera GX
Version: Latest Build

**Possible Solution**

Likely an issue with the while loop in the file

**Related Issues**

None

**Priority**

High

**Reproducibility**

Always

**Impact**

High

**Comment by hanaleiclark** [comment]
Infinite loop bug fixed by changing the binary expression in the function's while loop
