### ISSUE TITLE
remove_duplicates.cc Bug Report

### ISSUE THREAD

**Issue by hanaleiclark** [DocDomergue/Open-Source-Project#6]
Description: The vector of unique integers printed at the end of remove_duplicates.cc includes 0 at the end when that was not an element in the original vector "arr."

Steps to Reproduce:
Call remove_duplicates with a vector of integers that does not include 0 as a value, and an empty removed_elements vector.
Loop through the returned vector and print it out.

Expected Behavior: The returned vector will print out each element from the original vector, excluding duplicates.

Actual Behavior: The returned vector prints out each element from the original vector excluding duplicates, as well as the value 0 as the last element.

Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: macOS
Browser: CLion

Possible Solution: changing the for loop in the remove_duplicates function to iterate until i<n instead of i<=n.

Priority: medium priority

Reproducibility: every time

Impact: medium impact

**Comment by aiqojo** [comment]
Bug fixed [here](https://github.com/DocDomergue/Open-Source-Project/commit/7e02008592e8b4684390d3c51f8c9dd9b77927c4). There was a `<=` instead of just a `<` in the for loop on line 10. This caused the bug since the loop was going out of bounds of the array that we were finding duplicates in.

**Comment by aiqojo** [comment]
This issue is closed.
