### ISSUE TITLE
Issue/Bug Report  -  datetime_convert.java

### ISSUE THREAD

**Issue by MatthewLucia** [DocDomergue/Open-Source-Project#7]
Description function is returning unexpected string

Expected Behavior return a fully formatted string

Actual Behavior original, unformatted string is returned

Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: Mac OS
Browser: Google Chrome
Version: 111.0.5563.64
Any other relevant information
Possible Solution change output

Related Issues Are there any related issues? If so, please link to them here.

Priority high priority

Reproducibility random

Impact What is the impact of this issue/bug? high

**Comment by hanaleiclark** [comment]
Fixed bug by changing output sent to system from the originally inputted dateStr to the modified formattedDate
